import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, MoveDown, Quote, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AlbaLayout, AlbaServiceCard, ScrollCue, SectionHeading } from "@/components/alba-site";
import { useAlbaDemo } from "@/components/alba-demo-context";
import { albaImages } from "@/lib/alba-images";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "ALBA WELLNESS | Korean Head Spa & Wellness" },
    { name: "description", content: "Experience premium Korean-inspired head spa and wellness treatments at ALBA WELLNESS in Ahmedabad." },
    { property: "og:title", content: "ALBA WELLNESS | Korean Head Spa & Wellness" },
    { property: "og:description", content: "A Korean-inspired head spa experience designed to relax the mind, nourish the scalp and restore your natural balance." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: HomePage,
});

function HomePage() {
  const { store } = useAlbaDemo();
  return <AlbaLayout dark>
    <section className="relative flex min-h-[720px] items-center overflow-hidden bg-ink text-ivory sm:min-h-[780px] lg:min-h-[850px]">
      <img src={albaImages.hero} width={1920} height={1200} alt="A head spa therapist tending to a guest" className="absolute inset-0 h-full w-full object-cover object-center" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,oklch(0.12_0.01_68/0.88)_0%,oklch(0.12_0.01_68/0.6)_42%,oklch(0.12_0.01_68/0.12)_100%)]" />
      <div className="alba-wrap relative z-10 pt-24">
        <div className="max-w-xl rise-in">
          <p className="flex items-center gap-3 text-[10px] font-medium tracking-[0.2em] text-champagne"><span className="h-px w-8 bg-champagne"/>KOREAN HEAD SPA & WELLNESS</p>
          <h1 className="editorial-title mt-7 text-6xl sm:text-7xl lg:text-[88px]">Restore your mind.<br/><span className="text-champagne">Rejuvenate</span><br/>your scalp.</h1>
          <p className="mt-7 max-w-md text-sm leading-7 text-ivory/75 sm:text-base">A Korean-inspired head spa experience designed to relax the mind, nourish the scalp and restore your natural balance.</p>
          <div className="mt-9 flex flex-wrap items-center gap-4"><Button asChild className="h-12 rounded-none bg-champagne px-6 text-[10px] font-semibold tracking-[0.12em] text-ink hover:bg-champagne/85"><Link to="/booking">BOOK AN APPOINTMENT <ArrowRight/></Link></Button><Link to="/services" className="border-b border-ivory/45 pb-2 text-[10px] tracking-[0.14em] text-ivory no-underline hover:border-champagne hover:text-champagne">EXPLORE TREATMENTS</Link></div>
          <div className="mt-14 flex items-center gap-4 text-xs text-ivory/65"><span className="flex -space-x-2"><span className="grid size-8 place-items-center rounded-full border border-ink bg-ivory/15 text-[10px]">M</span><span className="grid size-8 place-items-center rounded-full border border-ink bg-champagne/35 text-[10px]">A</span><span className="grid size-8 place-items-center rounded-full border border-ink bg-ivory/25 text-[10px]">S</span></span><span><strong className="text-ivory">4.9 / 5</strong><br/>A ritual guests return to</span><span className="ml-5 hidden h-8 w-px bg-ivory/20 sm:block"/><span className="hidden sm:block"><strong className="text-ivory">60 minutes</strong><br/>to feel like yourself again</span></div>
        </div>
      </div><ScrollCue />
      <div className="absolute right-8 top-1/2 hidden -translate-y-1/2 rotate-90 text-[9px] tracking-[0.2em] text-ivory/45 xl:block">A MOMENT, JUST FOR YOU — AHMEDABAD</div>
    </section>

    <section className="alba-section bg-background"><div className="alba-wrap grid gap-12 lg:grid-cols-[1fr_1.15fr] lg:items-center lg:gap-20"><div className="relative"><img src={albaImages.interior} width={1200} height={1008} loading="lazy" alt="A quiet private ALBA head spa treatment room" className="aspect-[4/5] w-full object-cover"/><div className="absolute -bottom-5 right-0 hidden w-44 bg-ivory px-5 py-4 text-center sm:block"><span className="font-display text-3xl">A slower kind of care</span></div></div><div><p className="alba-eyebrow">A return to balance</p><h2 className="editorial-title mt-5 text-5xl sm:text-6xl">Where wellness<br/>begins at the roots.</h2><p className="mt-6 text-sm leading-7 text-muted-foreground">Rooted in the Korean head spa tradition, each ALBA ritual brings together thoughtful scalp care, water therapy and restorative touch. Nothing rushed. Nothing routine. Just a quiet, private moment shaped around how you feel.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">Step away from the noise, settle into a warm towel, and let your mind follow your body into stillness.</p><Button asChild variant="link" className="mt-7 h-auto px-0 text-xs tracking-[0.1em]"><Link to="/about">OUR APPROACH <ArrowRight/></Link></Button></div></div></section>

    <section className="alba-section dark-panel"><div className="alba-wrap"><div className="flex flex-col gap-7 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="The ALBA edit" title="Rituals, made personal." body="A considered collection of head spa and scalp rituals. Find the one that meets you where you are."/><Button asChild variant="outline" className="w-fit rounded-none border-ivory/35 text-ivory hover:bg-ivory hover:text-ink"><Link to="/services">VIEW ALL TREATMENTS <ArrowRight/></Link></Button></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{store.services.slice(0, 3).map((service) => <AlbaServiceCard key={service.id} service={service}/>)}</div></div></section>

    <section className="alba-section"><div className="alba-wrap grid gap-14 lg:grid-cols-2 lg:items-center"><div><p className="alba-eyebrow">The experience</p><h2 className="editorial-title mt-5 text-5xl sm:text-6xl">Your 60 minutes<br/>of complete reset.</h2><p className="mt-6 max-w-lg text-sm leading-7 text-muted-foreground">Warm water, mindful hands and the soft hush of a private treatment room. Every detail is chosen to help you feel held, cared for and wholly present.</p><div className="mt-8 grid grid-cols-2 gap-y-5 border-t border-border pt-7"><div><p className="font-display text-3xl">01</p><p className="mt-1 text-xs text-muted-foreground">Arrive and exhale</p></div><div><p className="font-display text-3xl">02</p><p className="mt-1 text-xs text-muted-foreground">Settle into your ritual</p></div><div><p className="font-display text-3xl">03</p><p className="mt-1 text-xs text-muted-foreground">Leave feeling lighter</p></div><div><p className="font-display text-3xl">04</p><p className="mt-1 text-xs text-muted-foreground">Carry calm with you</p></div></div></div><div className="relative"><img src={albaImages.ritual} width={1200} height={1008} loading="lazy" alt="Warm water poured as part of a Korean head spa ritual" className="aspect-[4/3] w-full object-cover"/><div className="absolute bottom-5 left-5 flex items-center gap-3 bg-ivory px-4 py-3"><Sparkles className="size-4 text-forest"/><span className="text-xs">A private ritual, thoughtfully yours</span></div></div></div></section>

    <section className="alba-section bg-secondary/60"><div className="alba-wrap"><div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-end"><div><p className="alba-eyebrow">A welcome from us</p><h2 className="editorial-title mt-4 text-5xl sm:text-6xl">A first visit,<br/>made special.</h2></div><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-sm text-sm leading-7 text-muted-foreground">Begin with the Signature Korean Head Spa and enjoy a little something from us on your first visit.</p><div className="min-w-52 border border-champagne bg-background px-6 py-5"><span className="alba-eyebrow">FIRST VISIT RITUAL</span><p className="mt-2 font-display text-4xl">20% OFF</p><p className="mt-1 text-[10px] text-muted-foreground">Code FIRSTVISIT20</p></div></div></div><div className="mt-11 grid grid-cols-2 gap-3 sm:grid-cols-4">{[albaImages.treatment, albaImages.interior, albaImages.ritual, albaImages.hero].map((image, i) => <img key={image} src={image} width={i === 3 ? 1920 : 1200} height={i === 3 ? 1200 : 1008} loading="lazy" alt={["Head spa treatment", "Private spa room", "Warm water ritual", "Relaxing spa experience"][i] ?? "ALBA Wellness"} className={`aspect-[4/3] w-full object-cover ${i === 1 ? "sm:mt-7" : i === 3 ? "sm:-mt-7" : ""}`}/>)}</div><Link to="/offers" className="mt-6 inline-flex items-center gap-2 text-xs text-foreground no-underline hover:text-forest">Explore all offers <ArrowRight className="size-3"/></Link></div></section>

    <section className="alba-section"><div className="alba-wrap"><SectionHeading eyebrow="Kind words" title="A little more like yourself." body="A few notes from guests who made time for a moment of care." align="center"/><div className="mt-12 grid gap-px border border-border bg-border sm:grid-cols-3">{store.reviews.filter((review) => review.featured).slice(0, 3).map((review) => <article key={review.id} className="bg-background p-7 sm:p-9"><Quote className="size-5 text-champagne"/><p className="mt-5 text-sm leading-7 text-muted-foreground">“{review.quote}”</p><div className="mt-7 alba-rule pt-4"><p className="text-sm font-medium">{review.customer}</p><p className="mt-1 text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{review.service}</p></div></article>)}</div><div className="mt-7 text-center"><Link to="/reviews" className="text-xs text-foreground no-underline hover:text-forest">Read guest notes <ArrowRight className="ml-1 inline size-3"/></Link></div></div></section>

    <section className="dark-panel"><div className="alba-wrap grid gap-0 py-14 sm:grid-cols-2 sm:items-center sm:gap-14 sm:py-20"><div><p className="alba-eyebrow">Find your quiet</p><h2 className="editorial-title mt-4 text-5xl sm:text-6xl">Your wellness<br/>journey starts here.</h2><p className="mt-5 max-w-sm text-sm leading-7 text-ivory/65">A private treatment room in Ahmedabad, waiting just for you.</p><Button asChild className="mt-7 rounded-none bg-champagne text-ink hover:bg-champagne/85"><Link to="/booking">BOOK YOUR APPOINTMENT <ArrowRight/></Link></Button></div><div className="mt-10 border-t border-ivory/15 pt-7 text-sm leading-7 text-ivory/70 sm:mt-0 sm:border-t-0 sm:border-l sm:pl-12 sm:pt-0"><p className="text-ivory">ALBA WELLNESS</p><p>Ahmedabad, Gujarat, India</p><p>Every day · 10:00 AM–8:00 PM</p><Link to="/contact" className="mt-3 inline-flex items-center gap-2 text-xs text-champagne no-underline">Plan your visit <ArrowRight className="size-3"/></Link><p className="mt-8 flex items-center gap-2 text-[10px] text-ivory/45"><MoveDown className="size-3"/>Your time, your way.</p></div></div></section>
  </AlbaLayout>;
}