import { useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Download, FileText, Heart, MapPin, MessageCircle, Minus, Phone, Plus, ShieldCheck, Sparkles, Star, UserRound, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { AlbaFooter, AlbaHeader, AlbaLayout, AlbaServiceCard, SectionHeading } from "@/components/alba-site";
import { useAlbaDemo } from "@/components/alba-demo-context";
import { formatRupees, getService, prettyDate, therapists, type AlbaAppointment, type AlbaService } from "@/lib/alba-demo";
import { albaImages } from "@/lib/alba-images";
import { toast } from "sonner";

const fieldClass = "h-11 rounded-none border-border bg-background";
const heroBlock = "relative flex min-h-[460px] items-end overflow-hidden bg-ink pb-14 pt-28 text-ivory sm:min-h-[520px] sm:pb-20";

export function InteriorPage({ eyebrow, title, description, children, dark = false }: { eyebrow: string; title: string; description?: string; children?: React.ReactNode; dark?: boolean }) {
  return <AlbaLayout dark><section className={`${heroBlock} ${dark ? "" : "!min-h-[360px] !pb-12"}`}><div className="alba-wrap relative z-10"><p className="alba-eyebrow">{eyebrow}</p><h1 className="editorial-title mt-4 max-w-3xl text-5xl sm:text-7xl">{title}</h1>{description && <p className="mt-5 max-w-xl text-sm leading-7 text-ivory/70">{description}</p>}</div></section>{children}</AlbaLayout>;
}

export function AboutPage() {
  return <InteriorPage eyebrow="The ALBA way" title="A softer pace. A deeper kind of care." description="An intimate Korean-inspired head spa, created for the moments when you need to return to yourself.">
    <section className="alba-section"><div className="alba-wrap grid gap-12 lg:grid-cols-2 lg:items-center"><img src={albaImages.interior} width={1200} height={1008} alt="ALBA Wellness treatment room" className="aspect-[4/3] w-full object-cover"/><div><p className="alba-eyebrow">Our story</p><h2 className="editorial-title mt-4 text-5xl">Care that starts at the roots.</h2><p className="mt-6 text-sm leading-7 text-muted-foreground">ALBA began with a simple belief: feeling well can start with making space for one small, unhurried thing. Inspired by the care and intention of the Korean head spa, we made a private sanctuary where scalp wellness and full-body relaxation meet.</p><p className="mt-4 text-sm leading-7 text-muted-foreground">Our vision is a gentler kind of wellness. Our mission is to make every visit feel personal, considered and easy to return to.</p></div></div></section>
    <section className="alba-section dark-panel"><div className="alba-wrap grid gap-8 sm:grid-cols-3">{[["Thoughtful touch", "Techniques chosen for comfort, not a one-size-fits-all routine."], ["A calm of your own", "A quiet private room, warmed towels and time without hurry."], ["Care in the details", "Premium products, attentive therapists and a ritual shaped around you."]].map(([title, text]) => <article key={title} className="border-t border-champagne/60 pt-5"><p className="font-display text-3xl">{title}</p><p className="mt-3 text-sm leading-6 text-ivory/60">{text}</p></article>)}</div></section>
    <section className="alba-section"><div className="alba-wrap flex flex-col items-start justify-between gap-7 sm:flex-row sm:items-end"><SectionHeading eyebrow="Our approach" title="A ritual, never a routine." body="Your therapist listens first, then adapts the pressure, products and pace to what feels right for you."/><Button asChild className="rounded-none"><Link to="/booking">MEET YOUR MOMENT <ArrowRight/></Link></Button></div></section>
  </InteriorPage>;
}

export function ServicesPage() {
  const { store } = useAlbaDemo();
  const [filter, setFilter] = useState("All");
  const filters = ["All", "Head Spa", "Scalp Care", "Relaxation", "Wellness", "Packages"];
  const services = store.services.filter((service) => service.active && (filter === "All" || service.category === filter));
  return <InteriorPage eyebrow="Treatments" title="Find the ritual that feels right." description="Considered head spa and scalp rituals, each shaped to help you feel more rested, more balanced, more yourself.">
    <section className="alba-section"><div className="alba-wrap"><div className="flex flex-wrap gap-2" role="group" aria-label="Filter treatments">{filters.map((item) => <Button key={item} onClick={() => setFilter(item)} variant={filter === item ? "default" : "outline"} className="h-9 rounded-none px-4 text-xs">{item}</Button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map((service) => <AlbaServiceCard key={service.id} service={service}/>)}</div>{services.length === 0 && <p className="py-16 text-center text-sm text-muted-foreground">There are no treatments in this collection right now.</p>}</div></section>
  </InteriorPage>;
}

export function ServiceDetailPage({ serviceId }: { serviceId?: string }) {
  const params = useParams({ strict: false }) as { serviceId?: string };
  const { store } = useAlbaDemo();
  const service = getService(store, serviceId ?? params.serviceId ?? "signature");
  const image = albaImages[service.image as keyof typeof albaImages] ?? albaImages.treatment;
  return <InteriorPage eyebrow={service.category} title={service.name} description={service.description}>
    <section className="alba-section"><div className="alba-wrap grid gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-start"><img src={image} width={1200} height={1008} alt={service.name} className="aspect-[4/3] w-full object-cover"/><div><div className="flex flex-wrap gap-5 text-xs text-muted-foreground"><span className="inline-flex items-center gap-2"><Clock3 className="size-4 text-forest"/>{service.duration} minutes</span><span className="inline-flex items-center gap-2"><Sparkles className="size-4 text-forest"/>Personalised ritual</span></div><p className="mt-5 font-display text-5xl">{formatRupees(service.price)}</p><p className="mt-4 text-sm leading-7 text-muted-foreground">A considered treatment in a private room, with every step guided by your comfort.</p><div className="mt-7"><p className="alba-eyebrow">The feeling after</p><div className="mt-3 grid gap-2">{service.benefits.map((benefit) => <p key={benefit} className="flex items-center gap-2 text-sm"><Check className="size-4 text-forest"/>{benefit}</p>)}</div></div><div className="mt-7"><p className="alba-eyebrow">Your ritual includes</p><p className="mt-3 text-sm leading-7 text-muted-foreground">A warm welcome, gentle scalp cleanse, soothing water therapy, personalised massage and a quiet moment to re-enter the day.</p></div><Button asChild className="mt-8 h-12 w-full rounded-none"><Link to="/booking" search={{ service: service.id }}>BOOK THIS TREATMENT <ArrowRight/></Link></Button><p className="mt-3 text-center text-[10px] text-muted-foreground">No payment is taken now · Choose your payment option at booking</p></div></div></section>
  </InteriorPage>;
}

export function OffersPage() {
  const { store } = useAlbaDemo();
  const active = store.offers.filter((offer) => offer.active);
  return <InteriorPage eyebrow="Thoughtful little extras" title="A welcome, from ALBA." description="A few ways to make your next moment of care feel even more special.">
    <section className="alba-section"><div className="alba-wrap grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{active.map((offer, i) => <article key={offer.id} className="bg-background p-7 sm:p-9"><span className="alba-eyebrow">{i === 0 ? "For your first visit" : "A little something"}</span><h2 className="editorial-title mt-5 text-4xl">{offer.name}</h2><p className="mt-3 font-display text-4xl text-forest">{offer.discount}</p><p className="mt-4 text-xs text-muted-foreground">Use code <strong className="font-semibold text-foreground">{offer.code}</strong> when booking.</p><Button asChild variant="link" className="mt-5 h-auto px-0 text-xs"><Link to="/booking">BOOK A RITUAL <ArrowRight/></Link></Button></article>)}</div></section>
  </InteriorPage>;
}

export function GalleryPage() {
  const images = [albaImages.treatment, albaImages.interior, albaImages.ritual, albaImages.hero, albaImages.interior, albaImages.treatment];
  const labels = ["The quiet of a scalp ritual", "A room of your own", "Warm water, mindful touch", "A pause in the day", "Every detail considered", "Care that starts at the roots"];
  return <InteriorPage eyebrow="Our space" title="A sanctuary for the senses." description="Warm towels, considered details and a private room where the outside world can wait.">
    <section className="alba-section"><div className="alba-wrap columns-1 gap-4 sm:columns-2 lg:columns-3">{images.map((image, i) => <figure key={`${image}-${i}`} className="mb-4 break-inside-avoid"><img src={image} width={i === 3 ? 1920 : 1200} height={i === 3 ? 1200 : 1008} loading="lazy" alt={labels[i] ?? "ALBA Wellness spa"} className={`w-full object-cover ${i % 3 === 0 ? "aspect-[4/5]" : "aspect-[4/3]"}`}/><figcaption className="mt-2 text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{labels[i]}</figcaption></figure>)}</div></section>
  </InteriorPage>;
}

export function ReviewsPage() {
  const { store } = useAlbaDemo();
  return <InteriorPage eyebrow="Kind words" title="Stories from our guests." description="Small notes from people who made time for themselves at ALBA WELLNESS.">
    <section className="alba-section"><div className="alba-wrap grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{store.reviews.filter((review) => review.featured).map((review) => <article key={review.id} className="bg-background p-7"><div className="flex gap-1" aria-label={`${review.rating} out of 5 stars`}>{Array.from({ length: review.rating }, (_, i) => <Star key={i} className="size-3 fill-champagne text-champagne"/>)}</div><p className="mt-5 text-sm leading-7 text-muted-foreground">“{review.quote}”</p><p className="mt-6 text-sm font-medium">{review.customer}</p><p className="mt-1 text-[10px] text-muted-foreground">{review.service}</p></article>)}</div></section>
  </InteriorPage>;
}

export function ContactPage() {
  const [sent, setSent] = useState(false);
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSent(true); toast.success("Thank you. Our team will get back to you shortly."); }
  return <InteriorPage eyebrow="Come as you are" title="We’d love to welcome you." description="Questions about a ritual, a first visit, or simply finding us? We’re here to help.">
    <section className="alba-section"><div className="alba-wrap grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div className="grid content-start gap-7">{[[MapPin, "Find us", "Ahmedabad, Gujarat, India"], [Clock3, "Opening hours", "Monday – Sunday · 10:00 AM – 8:00 PM"], [Phone, "Call us", "+91 XXXXX XXXXX"], [MessageCircle, "Write to us", "hello@alba-wellness.com"]].map(([Icon, title, text]) => { const IconComponent = Icon as typeof MapPin; return <div key={title as string} className="flex gap-4"><IconComponent className="mt-1 size-4 text-forest"/><div><p className="text-sm font-medium">{title as string}</p><p className="mt-1 text-sm text-muted-foreground">{text as string}</p></div></div>; })}<div className="mt-3 flex aspect-[16/7] items-center justify-center border border-border bg-secondary/70"><div className="text-center"><MapPin className="mx-auto size-6 text-forest"/><p className="mt-2 text-xs">Ahmedabad, Gujarat</p><p className="mt-1 text-[10px] text-muted-foreground">ALBA WELLNESS · Open every day</p></div></div></div><form onSubmit={submit} className="grid content-start gap-5 border border-border bg-card p-6 sm:p-9"><div><p className="alba-eyebrow">A note to our team</p><h2 className="editorial-title mt-3 text-4xl">How can we help?</h2></div><div className="grid gap-2"><Label htmlFor="contact-name">Your name</Label><Input required id="contact-name" className={fieldClass} placeholder="Name"/></div><div className="grid gap-2 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="contact-phone">Phone</Label><Input required id="contact-phone" type="tel" className={fieldClass} placeholder="+91"/></div><div className="grid gap-2"><Label htmlFor="contact-email">Email</Label><Input required id="contact-email" type="email" className={fieldClass} placeholder="you@example.com"/></div></div><div className="grid gap-2"><Label htmlFor="contact-message">Message</Label><textarea required id="contact-message" rows={4} className="resize-y border border-input bg-background px-3 py-3 text-sm outline-none focus-visible:ring-1 focus-visible:ring-ring" placeholder="Tell us a little about what you need"/></div><Button type="submit" className="h-11 rounded-none">{sent ? "MESSAGE RECEIVED" : "SEND YOUR NOTE"} <ArrowRight/></Button></form></div></section>
  </InteriorPage>;
}

const timeSlots = ["10:00 AM", "11:00 AM", "12:30 PM", "2:00 PM", "3:30 PM", "5:00 PM", "6:30 PM", "7:30 PM"];

function localDate(offset = 0) { const date = new Date(); date.setDate(date.getDate() + offset); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }

export function BookingPage() {
  const { store, addBooking } = useAlbaDemo();
  const navigate = useNavigate();
  const search = new URLSearchParams(typeof window === "undefined" ? "" : window.location.search);
  const [step, setStep] = useState(0);
  const [serviceId, setServiceId] = useState(search.get("service") ?? "signature");
  const [date, setDate] = useState(localDate(1));
  const [time, setTime] = useState("");
  const [therapist, setTherapist] = useState("Any Available Therapist");
  const [addons, setAddons] = useState<string[]>([]);
  const [payMethod, setPayMethod] = useState("deposit");
  const [processing, setProcessing] = useState(false);
  const [form, setForm] = useState({ name: "", phone: "", email: "", dob: "", note: "", firstVisit: true });
  const service = getService(store, serviceId);
  const total = service.price + service.addOns.filter((addon) => addons.includes(addon.name)).reduce((sum, addon) => sum + addon.price, 0);
  const steps = ["Treatment", "Date & time", "Therapist", "Extras", "Your details", "Payment"];
  const bookedForSelected = useMemo(() => store.appointments.filter((appointment) => appointment.date === date && appointment.status !== "Cancelled"), [date, store.appointments]);
  const availableSlots = timeSlots.map((slot, i) => ({ slot, status: bookedForSelected.some((appointment) => appointment.time === slot && (therapist === "Any Available Therapist" || appointment.therapist === therapist)) ? "Booked" : i === 2 ? "Almost full" : "Available" }));

  function next() {
    if (step === 0 && !serviceId) return toast.error("Please choose a treatment to continue.");
    if (step === 1 && !time) return toast.error("Choose an available time for your visit.");
    if (step === 4 && (!form.name.trim() || !form.phone.trim() || !/\S+@\S+\.\S+/.test(form.email))) return toast.error("Add your name, a phone number and a valid email.");
    setStep((current) => Math.min(current + 1, 5));
  }

  async function confirm() {
    setProcessing(true);
    await new Promise((resolve) => window.setTimeout(resolve, 800));
    const amount = payMethod === "deposit" ? Math.round(total * 0.3) : payMethod === "spa" ? 0 : total;
    addBooking({ customer: form.name, phone: form.phone, email: form.email, serviceId: service.id, date, time, therapist: therapist === "Any Available Therapist" ? therapists[0] ?? "Maya Sharma" : therapist, amount });
    setProcessing(false);
    toast.success("Appointment successfully booked.");
    navigate({ to: "/booking/success" });
  }

  return <AlbaLayout dark><section className="dark-panel min-h-[300px] pt-28"><div className="alba-wrap py-7"><p className="alba-eyebrow">Your moment of calm</p><h1 className="editorial-title mt-3 text-5xl sm:text-6xl">Make time for you.</h1><p className="mt-3 text-sm text-ivory/65">A few thoughtful steps, and your ritual is reserved.</p></div></section><section className="min-h-[70vh] py-8 sm:py-12"><div className="alba-wrap grid gap-8 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start"><div className="min-w-0"><div className="mb-8 grid grid-cols-6 gap-1 sm:gap-3">{steps.map((label, i) => <button key={label} type="button" onClick={() => i < step && setStep(i)} className="group min-w-0 text-left" aria-label={`Step ${i + 1}: ${label}${i === step ? " current" : ""}`}><span className={`mb-2 grid size-8 place-items-center border text-xs ${i <= step ? "border-forest bg-forest text-ivory" : "border-border text-muted-foreground"}`}>{i < step ? <Check className="size-4"/> : i + 1}</span><span className={`hidden truncate text-[10px] sm:block ${i === step ? "font-semibold text-foreground" : "text-muted-foreground"}`}>{label}</span></button>)}</div>
      <div className="border border-border bg-card p-5 sm:p-8">
        {step === 0 && <div><StepTitle title="Choose your treatment" note="A ritual to meet you where you are."/><div className="mt-6 grid gap-3">{store.services.filter((item) => item.active).map((item) => <button key={item.id} type="button" onClick={() => setServiceId(item.id)} className={`grid grid-cols-[88px_minmax(0,1fr)_auto] items-center gap-3 border p-3 text-left transition-colors sm:grid-cols-[104px_minmax(0,1fr)_auto] sm:gap-5 ${serviceId === item.id ? "border-forest bg-secondary/55" : "border-border hover:border-foreground/30"}`}><img src={albaImages[item.image as keyof typeof albaImages] ?? albaImages.treatment} alt="" width={1200} height={1008} className="aspect-square w-full object-cover"/><span className="min-w-0"><span className="block truncate text-sm font-medium">{item.name}</span><span className="mt-1 block text-xs text-muted-foreground">{item.duration} min · {item.category}</span><span className="mt-2 block text-sm">{formatRupees(item.price)}</span></span><span className={`grid size-5 place-items-center rounded-full border ${serviceId === item.id ? "border-forest bg-forest text-ivory" : "border-border"}`}>{serviceId === item.id && <Check className="size-3"/>}</span></button>)}</div></div>}
        {step === 1 && <div><StepTitle title="Choose a date & time" note="Select an available appointment. Past dates are not available."/><div className="mt-6 grid gap-5"><div className="grid gap-2"><Label htmlFor="booking-date">Appointment date</Label><Input id="booking-date" type="date" min={localDate(1)} value={date} onChange={(event) => { setDate(event.target.value); setTime(""); }} className={fieldClass}/></div><div><div className="mb-3 flex items-center gap-2 text-sm font-medium"><CalendarDays className="size-4 text-forest"/>{prettyDate(date)}</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{availableSlots.map(({ slot, status }) => <button key={slot} disabled={status === "Booked"} type="button" onClick={() => setTime(slot)} className={`min-h-14 border px-3 py-2 text-left ${time === slot ? "border-forest bg-forest text-ivory" : status === "Booked" ? "border-border bg-secondary/40 text-muted-foreground opacity-50" : "border-border hover:border-forest"}`}><span className="block text-xs font-medium">{slot}</span><span className="mt-1 block text-[9px]">{time === slot ? "Selected" : status}</span></button>)}</div></div><p className="text-xs text-muted-foreground">Treatment time: {service.duration} minutes · We’ll confirm your therapist in the next step.</p></div></div>}
        {step === 2 && <div><StepTitle title="A therapist for your ritual" note="Choose a specialist or leave it to us."/><div className="mt-6 grid gap-3 sm:grid-cols-2">{["Any Available Therapist", ...therapists].map((name, i) => <button key={name} type="button" onClick={() => setTherapist(name)} className={`flex min-h-20 items-center gap-3 border p-4 text-left ${therapist === name ? "border-forest bg-secondary/50" : "border-border hover:border-foreground/30"}`}><span className="grid size-10 shrink-0 place-items-center rounded-full bg-secondary text-forest">{i === 0 ? <UsersRound className="size-4"/> : <UserRound className="size-4"/>}</span><span className="min-w-0"><span className="block text-sm font-medium">{name}</span><span className="mt-1 block text-[10px] text-muted-foreground">{i === 0 ? "We’ll find the right specialist" : store.staff.find((member) => member.name === name)?.specialty ?? "Wellness Therapist"}</span></span>{therapist === name && <Check className="ml-auto size-4 shrink-0 text-forest"/>}</button>)}</div></div>}
        {step === 3 && <div><StepTitle title="Make it your own" note="Optional additions to personalise your experience."/><div className="mt-6 grid gap-3">{service.addOns.map((addon) => <label key={addon.name} className="flex cursor-pointer items-center justify-between gap-4 border border-border p-4"><span className="flex items-center gap-3"><Checkbox checked={addons.includes(addon.name)} onCheckedChange={(checked) => setAddons((list) => checked ? [...list, addon.name] : list.filter((name) => name !== addon.name))}/><span><span className="block text-sm">{addon.name}</span><span className="mt-1 block text-[10px] text-muted-foreground">An optional finishing touch</span></span></span><span className="shrink-0 text-sm">+{formatRupees(addon.price)}</span></label>)}</div><button type="button" className="mt-5 text-xs text-muted-foreground underline underline-offset-4" onClick={() => setAddons([])}>Continue without additions</button></div>}
        {step === 4 && <div><StepTitle title="A few details, please" note="We’ll use these to prepare for your visit."/><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["Full name", "name", "text", "Your name"], ["Phone", "phone", "tel", "+91"], ["Email", "email", "email", "you@example.com"], ["Date of birth · optional", "dob", "date", ""]].map(([label, key, type, placeholder]) => <div key={key} className="grid gap-2"><Label htmlFor={`customer-${key}`}>{label}</Label><Input id={`customer-${key}`} type={type} placeholder={placeholder} required={key !== "dob"} value={form[key as keyof typeof form] as string} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className={fieldClass}/></div>)}<div className="grid gap-2 sm:col-span-2"><Label htmlFor="special-request">Special requests · optional</Label><textarea id="special-request" rows={3} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Anything you’d like us to know before your visit?" className="resize-y border border-input bg-background px-3 py-3 text-sm outline-none focus-visible:ring-1 focus-visible:ring-ring"/></div><label className="flex items-center gap-3 text-xs text-muted-foreground sm:col-span-2"><Checkbox checked={form.firstVisit} onCheckedChange={(checked) => setForm({ ...form, firstVisit: checked === true })}/>This is my first visit to ALBA</label></div></div>}
        {step === 5 && <div><StepTitle title="Confirm your ritual" note="Choose how you’d like to take care of payment."/><div className="mt-6 grid gap-3">{[["full", "Pay full amount", total], ["deposit", "Pay 30% deposit", Math.round(total * 0.3)], ["spa", "Pay at the spa", 0]].map(([method, label, amount]) => <button key={method} type="button" onClick={() => setPayMethod(String(method))} className={`flex items-center justify-between border p-4 text-left ${payMethod === method ? "border-forest bg-secondary/45" : "border-border"}`}><span><span className="block text-sm font-medium">{label as string}</span><span className="mt-1 block text-[10px] text-muted-foreground">{method === "spa" ? "Settle at your appointment" : "Secure demo payment"}</span></span><span className="flex items-center gap-2 text-sm">{formatRupees(Number(amount))}<span className={`grid size-4 place-items-center rounded-full border ${payMethod === method ? "border-forest bg-forest text-ivory" : "border-border"}`}>{payMethod === method && <Check className="size-3"/>}</span></span></button>)}</div><div className="mt-6 flex items-start gap-3 border border-border bg-secondary/35 p-4"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-forest"/><p className="text-xs leading-5 text-muted-foreground">This is a demo payment. No card will be charged and your details are not sent anywhere.</p></div><div className="mt-6 border-t border-border pt-5"><p className="alba-eyebrow">Appointment summary</p><p className="mt-3 text-sm font-medium">{service.name}</p><p className="mt-1 text-xs text-muted-foreground">{prettyDate(date)} · {time} · {therapist}</p></div></div>}
        <div className="mt-8 flex flex-col-reverse gap-3 border-t border-border pt-5 sm:flex-row sm:justify-between">{step > 0 ? <Button variant="outline" className="rounded-none" onClick={() => setStep((current) => current - 1)}><ArrowLeft/> BACK</Button> : <span/>}{step < 5 ? <Button className="rounded-none" onClick={next}>CONTINUE <ArrowRight/></Button> : <Button className="rounded-none" disabled={processing} onClick={confirm}>{processing ? "RESERVING YOUR RITUAL…" : "CONFIRM APPOINTMENT"} <Check/></Button>}</div>
      </div></div>
      <aside className="lg:sticky lg:top-6"><div className="border border-border bg-card p-5 sm:p-6"><p className="alba-eyebrow">Your appointment</p><h2 className="mt-4 font-display text-3xl">{service.name}</h2><p className="mt-2 text-xs text-muted-foreground">{service.duration} minutes · {service.category}</p><div className="mt-5 grid gap-3 border-t border-border pt-4 text-xs"><p className="flex justify-between"><span className="text-muted-foreground">Treatment</span><span>{formatRupees(service.price)}</span></p>{service.addOns.filter((addon) => addons.includes(addon.name)).map((addon) => <p key={addon.name} className="flex justify-between"><span className="text-muted-foreground">{addon.name}</span><span>{formatRupees(addon.price)}</span></p>)}<p className="flex justify-between border-t border-border pt-3 text-sm font-semibold"><span>Total</span><span>{formatRupees(total)}</span></p></div><img src={albaImages.interior} width={1200} height={1008} alt="Private ALBA Wellness room" className="mt-5 aspect-[16/9] w-full object-cover"/><p className="mt-4 text-[10px] leading-5 text-muted-foreground">A calm, private treatment room in Ahmedabad. Every day, 10:00 AM–8:00 PM.</p></div></aside></div></section></AlbaLayout>;
}

function StepTitle({ title, note }: { title: string; note: string }) { return <div><h2 className="font-display text-3xl sm:text-4xl">{title}</h2><p className="mt-2 text-xs text-muted-foreground">{note}</p></div>; }

export function BookingSuccessPage() {
  const { store } = useAlbaDemo();
  const booking = store.appointments[0];
  const service = booking ? getService(store, booking.serviceId) : getService(store, "signature");
  function downloadInvoice() { const text = `ALBA WELLNESS\nKorean Head Spa & Wellness\n\nInvoice · ${booking?.reference ?? "ALBA-2026-10482"}\nCustomer: ${booking?.customer ?? store.profile.name}\nService: ${service.name}\nDate: ${booking ? prettyDate(booking.date) : "To be confirmed"} · ${booking?.time ?? ""}\nTotal: ${formatRupees(booking?.amount ?? service.price)}\n\nThank you for choosing ALBA WELLNESS.\nTechnology Platform by INFIYOURA`; const blob = new Blob([text], { type: "text/plain" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${booking?.reference ?? "ALBA-invoice"}.txt`; a.click(); URL.revokeObjectURL(url); toast.success("Your invoice is ready to download."); }
  function downloadCalendar() { if (!booking) return; const content = `BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nSUMMARY:ALBA WELLNESS · ${service.name}\nDTSTART:${booking.date.replaceAll("-", "")}T100000\nDESCRIPTION:${booking.reference}\nEND:VEVENT\nEND:VCALENDAR`; const blob = new Blob([content], { type: "text/calendar" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "alba-appointment.ics"; a.click(); URL.revokeObjectURL(url); toast.success("Appointment calendar file downloaded."); }
  return <InteriorPage eyebrow="It’s a date" title="You’re all set." description="Your wellness experience has been reserved. We look forward to welcoming you." dark><section className="alba-section"><div className="alba-wrap max-w-3xl"><div className="border border-border bg-card p-6 sm:p-10"><div className="flex flex-col gap-5 border-b border-border pb-7 sm:flex-row sm:items-center sm:justify-between"><div><span className="grid size-12 place-items-center rounded-full bg-forest text-ivory"><Check/></span><p className="mt-4 text-xs text-muted-foreground">BOOKING REFERENCE</p><p className="mt-1 font-display text-3xl">{booking?.reference ?? "ALBA-2026-10482"}</p></div><div className="border border-forest/30 bg-forest/5 px-4 py-3 text-xs text-forest"><p>✓ Confirmation email prepared</p><p className="mt-2">✓ WhatsApp confirmation prepared</p><p className="mt-2">✓ Invoice generated</p></div></div><div className="grid gap-5 py-7 sm:grid-cols-2"><Summary label="Treatment" value={service.name}/><Summary label="Date & time" value={booking ? `${prettyDate(booking.date)} · ${booking.time}` : "To be confirmed"}/><Summary label="Therapist" value={booking?.therapist ?? "Maya Sharma"}/><Summary label="Guest" value={booking?.customer ?? store.profile.name}/><Summary label="Amount" value={formatRupees(booking?.amount ?? service.price)}/><Summary label="Payment status" value={booking?.payment ?? "Paid"}/></div><div className="flex flex-wrap gap-3 border-t border-border pt-6"><Button onClick={downloadInvoice} className="rounded-none"><Download/> DOWNLOAD INVOICE</Button><Button variant="outline" className="rounded-none" onClick={downloadCalendar}><CalendarDays/> ADD TO CALENDAR</Button><Button asChild variant="outline" className="rounded-none"><Link to="/customer/bookings">VIEW APPOINTMENT <ArrowRight/></Link></Button></div></div><p className="mt-6 text-center text-xs text-muted-foreground">A note of confirmation is ready for your inbox and WhatsApp.</p><div className="mt-7 text-center"><Button asChild variant="link"><Link to="/">BACK TO ALBA <ArrowRight/></Link></Button></div></div></section></InteriorPage>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value}</p></div>; }

export function LoginPage() {
  const { setRole } = useAlbaDemo();
  const navigate = useNavigate();
  const demoRoles = [["Super Admin", "admin@alba-wellness.demo"], ["Receptionist", "reception@alba-wellness.demo"], ["Therapist", "therapist@alba-wellness.demo"], ["Accountant", "accounts@alba-wellness.demo"]];
  function enter(role: string) { setRole(role); toast.success(`Welcome to the ${role} demo.`); navigate({ to: role === "Therapist" ? "/staff" : role === "Customer" ? "/customer" : "/admin" }); }
  return <AlbaLayout dark><section className="grid min-h-[82vh] bg-ink pt-[76px] text-ivory lg:grid-cols-2"><div className="relative hidden overflow-hidden lg:block"><img src={albaImages.interior} width={1200} height={1008} alt="ALBA Wellness treatment room" className="absolute inset-0 h-full w-full object-cover opacity-80"/><div className="absolute inset-0 bg-ink/35"/><div className="absolute bottom-12 left-12 max-w-md"><p className="alba-eyebrow">A quieter kind of care</p><p className="editorial-title mt-4 text-5xl">Your moment<br/>is waiting.</p></div></div><div className="flex items-center justify-center px-5 py-12 sm:px-10"><div className="w-full max-w-md"><p className="alba-eyebrow">Welcome to ALBA</p><h1 className="editorial-title mt-4 text-5xl">Good to see you.</h1><p className="mt-3 text-sm text-ivory/60">Choose where you’d like to continue.</p><div className="mt-8 grid gap-3">{demoRoles.map(([role, email]) => <button key={role} onClick={() => enter(role)} className="flex min-h-16 items-center justify-between border border-ivory/20 px-4 text-left transition-colors hover:border-champagne"><span><span className="block text-sm">{role}</span><span className="mt-1 block text-[10px] text-ivory/45">{email} · password</span></span><ArrowRight className="size-4 text-champagne"/></button>)}<button onClick={() => enter("Customer")} className="flex min-h-16 items-center justify-between border border-champagne/50 px-4 text-left hover:bg-ivory/5"><span><span className="block text-sm">Continue as Customer</span><span className="mt-1 block text-[10px] text-ivory/45">Meera Patel · customer portal</span></span><Heart className="size-4 text-champagne"/></button></div><p className="mt-6 text-[10px] leading-5 text-ivory/45">Demo accounts are ready to explore. No real password or account is required.</p><div className="mt-7 text-[9px] tracking-[0.15em] text-ivory/45">TECHNOLOGY PARTNER · INFՅYOURA</div></div></div></section><AlbaFooter/></AlbaLayout>;
}

const customerTabs = [["Overview", "/customer"], ["Appointments", "/customer/bookings"], ["Profile", "/customer/profile"], ["Invoices", "/customer/invoices"]] as const;

export function CustomerPage({ view = "overview" }: { view?: string }) {
  const { store, updateStore, resetDemo } = useAlbaDemo();
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState(false);
  const [profile, setProfile] = useState(store.profile);
  const appointments = store.appointments.filter((appointment) => appointment.customer === store.profile.name || appointment.email === store.profile.email);
  const upcoming = appointments.find((appointment) => appointment.status === "Confirmed" || appointment.status === "Pending");
  const invoices = appointments.map((appointment) => ({ ...appointment, service: getService(store, appointment.serviceId) }));
  const shownAppointments = appointments.filter((item) => `${item.reference} ${item.customer} ${getService(store, item.serviceId).name}`.toLowerCase().includes(search.toLowerCase()));
  function updateStatus(appointment: AlbaAppointment, status: AlbaAppointment["status"]) { updateStore((current) => ({ ...current, appointments: current.appointments.map((item) => item.id === appointment.id ? { ...item, status } : item) })); toast.success(`Appointment ${status.toLowerCase()}.`); }
  function exportInvoice(appointment: AlbaAppointment) { const service = getService(store, appointment.serviceId); const body = `ALBA WELLNESS\nINVOICE ${appointment.reference}\nCustomer: ${appointment.customer}\nService: ${service.name}\nDate: ${prettyDate(appointment.date)} · ${appointment.time}\nAmount: ${formatRupees(appointment.amount)}\nPayment status: ${appointment.payment}\n\nThank you for choosing ALBA WELLNESS.\nTechnology Platform by INFIYOURA`; const blob = new Blob([body], { type: "text/plain" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${appointment.reference}.txt`; a.click(); URL.revokeObjectURL(url); toast.success("Invoice downloaded."); }
  return <AlbaLayout><section className="dark-panel pt-28"><div className="alba-wrap flex flex-col gap-5 py-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="alba-eyebrow">DEMO MODE · CUSTOMER</p><h1 className="editorial-title mt-3 text-5xl">Hello, {store.profile.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-ivory/60">Your next moment of calm is closer than you think.</p></div><Button asChild className="w-fit rounded-none bg-champagne text-ink"><Link to="/booking">BOOK A RITUAL <ArrowRight/></Link></Button></div></section><section className="min-h-[65vh] py-8"><div className="alba-wrap grid gap-8 lg:grid-cols-[220px_minmax(0,1fr)]"><nav className="flex gap-2 overflow-x-auto border-b border-border pb-3 lg:block lg:border-b-0 lg:pb-0" aria-label="Customer navigation">{customerTabs.map(([label, to]) => <Link key={to} to={to} className={`shrink-0 px-3 py-2 text-xs no-underline lg:mb-1 lg:block ${view === label.toLowerCase() || (view === "overview" && to === "/customer") ? "bg-secondary text-foreground" : "text-muted-foreground hover:text-foreground"}`}>{label}</Link>)}<button className="shrink-0 px-3 py-2 text-xs text-muted-foreground lg:mt-4" onClick={() => { resetDemo(); toast.success("Demo reset."); }}>Reset demo</button></nav><div className="min-w-0">
    {view === "overview" && <><SectionHeading eyebrow="Your ALBA moments" title="A little time, just for you." body="Your visits, thoughtful care and notes from the team, all in one place."/><div className="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Upcoming appointment", upcoming ? "1" : "—"], ["Previous visits", String(appointments.filter((x) => x.status === "Completed").length)], ["Total spent", formatRupees(appointments.filter((x) => x.payment === "Paid").reduce((sum, x) => sum + x.amount, 0))], ["ALBA moments", String(appointments.filter((x) => x.status === "Completed").length * 20) + " pts"]].map(([label, value]) => <div key={label} className="border border-border bg-card p-4"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl">{value}</p></div>)}</div>{upcoming ? <AppointmentCard appointment={upcoming} store={store} onCancel={() => updateStatus(upcoming, "Cancelled")} onInvoice={() => exportInvoice(upcoming)}/> : <div className="mt-7 border border-border bg-card p-8 text-center"><CalendarDays className="mx-auto size-6 text-forest"/><p className="mt-3 font-display text-3xl">No upcoming appointments</p><p className="mt-2 text-xs text-muted-foreground">Your next wellness experience will appear here.</p><Button asChild className="mt-5 rounded-none"><Link to="/booking">FIND YOUR RITUAL</Link></Button></div>}</>}
    {view === "bookings" && <><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3"><div><p className="alba-eyebrow">Your visits</p><h2 className="editorial-title mt-2 text-4xl">Appointments</h2></div><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search visits" className="w-full max-w-48 rounded-none"/></div><div className="mt-6 grid gap-4">{shownAppointments.map((appointment) => <AppointmentCard key={appointment.id} appointment={appointment} store={store} onCancel={() => updateStatus(appointment, "Cancelled")} onInvoice={() => exportInvoice(appointment)}/>)}</div></>}
    {view === "profile" && <><p className="alba-eyebrow">Your details</p><h2 className="editorial-title mt-2 text-4xl">Profile</h2><div className="mt-6 grid gap-4 border border-border bg-card p-6 sm:grid-cols-2">{([["Name", "name"], ["Phone", "phone"], ["Email", "email"], ["Date of birth", "dob"], ["Address", "address"]] as const).map(([label, key]) => <div key={key} className="grid gap-2"><Label htmlFor={`profile-${key}`}>{label}</Label><Input id={`profile-${key}`} type={key === "dob" ? "date" : "text"} value={profile[key]} onChange={(event) => setProfile({ ...profile, [key]: event.target.value })} className={fieldClass}/></div>)}<div className="flex items-end"><Button className="rounded-none" onClick={() => { updateStore((current) => ({ ...current, profile })); setEditing(false); toast.success("Your profile has been updated."); }}>SAVE CHANGES <Check/></Button></div></div></>}
    {view === "invoices" && <><p className="alba-eyebrow">Your records</p><h2 className="editorial-title mt-2 text-4xl">Invoices</h2><div className="mt-6 grid gap-3">{invoices.map((invoice) => <div key={invoice.id} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border border-border bg-card p-4 sm:grid-cols-[1fr_1fr_1fr_auto]"><span className="min-w-0"><span className="block truncate text-xs font-medium">{invoice.reference}</span><span className="mt-1 block text-[10px] text-muted-foreground">{prettyDate(invoice.date)}</span></span><span className="hidden text-xs sm:block">{invoice.service.name}</span><span className="text-xs">{formatRupees(invoice.amount)} · {invoice.payment}</span><Button variant="outline" size="sm" onClick={() => exportInvoice(invoice)} aria-label={`Download invoice ${invoice.reference}`}><Download/></Button></div>)}</div></>}
    </div></div></section></AlbaLayout>;
}

function AppointmentCard({ appointment, store, onCancel, onInvoice }: { appointment: AlbaAppointment; store: import("@/lib/alba-demo").AlbaDemoStore; onCancel: () => void; onInvoice: () => void }) {
  const service = getService(store, appointment.serviceId);
  return <article className="mt-6 grid gap-4 border border-border bg-card p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:p-6"><div><div className="flex flex-wrap items-center gap-3"><p className="font-display text-3xl">{service.name}</p><span className="border border-forest/30 px-2 py-1 text-[9px] uppercase tracking-[0.1em] text-forest">{appointment.status}</span></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground"><span className="inline-flex items-center gap-2"><CalendarDays className="size-3.5"/>{prettyDate(appointment.date)}</span><span className="inline-flex items-center gap-2"><Clock3 className="size-3.5"/>{appointment.time}</span><span>{appointment.therapist}</span></div><p className="mt-2 text-[10px] text-muted-foreground">{appointment.reference} · {formatRupees(appointment.amount)} · {appointment.payment}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={onInvoice}>INVOICE</Button>{appointment.status === "Confirmed" && <Button size="sm" variant="outline" onClick={() => toast.message("Please call us to reschedule your visit.", { description: "+91 XXXXX XXXXX · Every day, 10 AM–8 PM" })}>RESCHEDULE</Button>}{appointment.status === "Confirmed" && <Button size="sm" variant="outline" onClick={onCancel}>CANCEL</Button>}</div></article>;
}

const adminNav = [["Overview", "/admin"], ["Appointments", "/admin/appointments"], ["Services", "/admin/services"], ["Staff", "/admin/staff"], ["Customers", "/admin/customers"], ["Invoices", "/admin/invoices"], ["Offers", "/admin/offers"], ["Reviews", "/admin/reviews"], ["Reports", "/admin/reports"], ["Settings", "/admin/settings"]] as const;

export function AdminPage({ view = "overview" }: { view?: string }) {
  const { store, updateStore, resetDemo, role, setRole } = useAlbaDemo();
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [period, setPeriod] = useState("This month");
  const appointments = store.appointments.filter((item) => `${item.customer} ${item.reference} ${getService(store, item.serviceId).name}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All" || item.status === filter));
  const confirmed = store.appointments.filter((item) => item.status === "Confirmed").length;
  const completed = store.appointments.filter((item) => item.status === "Completed").length;
  const revenue = store.appointments.filter((item) => item.payment === "Paid").reduce((sum, item) => sum + item.amount, 0);
  const customers = new Set(store.appointments.map((item) => item.email)).size;
  function changeStatus(id: string, status: AlbaAppointment["status"]) { updateStore((current) => ({ ...current, appointments: current.appointments.map((item) => item.id === id ? { ...item, status } : item) })); toast.success(`Appointment marked ${status.toLowerCase()}.`); }
  function exportCsv() { const csv = ["Reference,Customer,Service,Date,Time,Therapist,Amount,Status,Payment", ...appointments.map((item) => [item.reference, item.customer, getService(store, item.serviceId).name, item.date, item.time, item.therapist, item.amount, item.status, item.payment].map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(","))].join("\n"); const blob = new Blob([csv], { type: "text/csv" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "alba-report.csv"; a.click(); URL.revokeObjectURL(url); toast.success("Report exported as CSV."); }
  return <div className="min-h-screen bg-secondary/35"><div className="grid min-h-screen lg:grid-cols-[244px_minmax(0,1fr)]"><aside className="dark-panel hidden flex-col p-5 lg:flex"><Link to="/" className="flex items-center gap-3 text-ivory no-underline"><span className="grid size-9 place-items-center border border-champagne/70 font-display text-xl text-champagne">A</span><span className="text-[11px] tracking-[0.16em]">ALBA WELLNESS</span></Link><p className="alba-eyebrow mt-9">MANAGEMENT</p><nav className="mt-3 grid gap-1">{adminNav.map(([label, to]) => <Link key={to} to={to} className={`px-3 py-2.5 text-xs no-underline ${view === (to === "/admin" ? "overview" : to.split("/").at(-1)) ? "bg-ivory/10 text-champagne" : "text-ivory/65 hover:bg-ivory/5 hover:text-ivory"}`}>{label}</Link>)}</nav><div className="mt-auto border-t border-ivory/10 pt-4"><p className="text-[10px] text-ivory/45">Technology partner</p><p className="mt-1 text-[10px] font-semibold tracking-[0.16em] text-ivory/70">INFIYOURA</p><Link to="/" className="mt-4 block text-[10px] text-ivory/45 no-underline hover:text-ivory">← Back to public site</Link></div></aside><main className="min-w-0"><header className="sticky top-0 z-20 flex min-h-[68px] items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur sm:px-8"><div className="flex min-w-0 items-center gap-3"><Button asChild variant="ghost" size="icon" className="shrink-0 lg:hidden"><Link to="/"><ArrowLeft/></Link></Button><div className="min-w-0"><p className="truncate text-[10px] text-muted-foreground">ALBA WELLNESS · DEMO MODE</p><p className="truncate text-sm font-medium">{view === "overview" ? "Management overview" : view.charAt(0).toUpperCase() + view.slice(1)}</p></div></div><div className="flex shrink-0 items-center gap-2"><select aria-label="Demo role" value={role === "Guest" ? "Super Admin" : role} onChange={(event) => setRole(event.target.value)} className="max-w-36 border border-border bg-background px-2 py-2 text-[10px]"><option>Super Admin</option><option>Receptionist</option><option>Therapist</option><option>Accountant</option></select><Button asChild size="sm" className="rounded-none"><Link to="/booking"><Plus/> NEW BOOKING</Link></Button></div></header><nav className="flex gap-1 overflow-x-auto border-b border-border bg-background px-3 py-2 lg:hidden">{adminNav.map(([label, to]) => <Link key={to} to={to} className="shrink-0 px-3 py-2 text-[10px] text-muted-foreground no-underline">{label}</Link>)}</nav><div className="p-4 sm:p-7 lg:p-9">
    {view === "overview" && <><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="alba-eyebrow">ALBA WELLNESS · MANAGEMENT</p><h1 className="editorial-title mt-2 text-4xl sm:text-5xl">Good morning.</h1><p className="mt-2 text-xs text-muted-foreground">Your studio at a glance.</p></div><p className="text-xs text-muted-foreground">{new Date().toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}</p></div><div className="mt-7 grid grid-cols-2 gap-3 xl:grid-cols-4">{[["Total bookings", store.appointments.length], ["Confirmed", confirmed], ["Completed", completed], ["Paid revenue", formatRupees(revenue)], ["Pending payment", store.appointments.filter((item) => item.payment === "Pending").length], ["New customers", customers], ["Active treatments", store.services.filter((item) => item.active).length], ["Unread notes", store.notifications.filter((item) => !item.read).length]].map(([label, value]) => <div key={label} className="border border-border bg-background p-4 sm:p-5"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-2 font-display text-3xl sm:text-4xl">{value}</p></div>)}</div><div className="mt-8 grid gap-5 xl:grid-cols-[1.4fr_0.6fr]"><div className="border border-border bg-background"><div className="flex items-center justify-between border-b border-border p-4 sm:p-5"><div><p className="text-sm font-medium">Recent appointments</p><p className="mt-1 text-[10px] text-muted-foreground">Latest activity in your studio</p></div><Button asChild variant="link" size="sm"><Link to="/admin/appointments">VIEW ALL <ArrowRight/></Link></Button></div><AppointmentList rows={store.appointments.slice(0, 6)} onStatus={changeStatus}/></div><div className="border border-border bg-background p-5"><p className="text-sm font-medium">Studio rhythm</p><p className="mt-1 text-[10px] text-muted-foreground">Bookings across the last seven days</p><MiniChart appointments={store.appointments}/><div className="mt-4 flex justify-between text-[10px] text-muted-foreground"><span>7 days ago</span><span>Today</span></div><div className="mt-6 border-t border-border pt-4"><p className="text-xs font-medium">Most loved ritual</p><p className="mt-2 font-display text-2xl">{popularService(store.appointments, store.services)}</p></div></div></div></>}
    {view === "appointments" && <><SectionHeading eyebrow="The day, thoughtfully managed" title="Appointments" body="Review each visit, update its status and keep your team in sync."/><div className="mt-6 grid grid-cols-[minmax(0,1fr)_auto] gap-3 sm:flex sm:items-center sm:justify-between"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search guest or treatment" className="rounded-none sm:max-w-72"/><select aria-label="Filter appointments by status" value={filter} onChange={(event) => setFilter(event.target.value)} className="border border-border bg-background px-3 text-xs">{["All", "Confirmed", "Pending", "Completed", "Cancelled", "No Show", "Rescheduled"].map((item) => <option key={item}>{item}</option>)}</select></div><div className="mt-5 border border-border bg-background"><AppointmentList rows={appointments} onStatus={changeStatus}/></div></>}
    {view === "services" && <><SectionHeading eyebrow="Your treatment menu" title="Services" body="The rituals available to your guests."/><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{store.services.map((service) => <ServiceAdminCard key={service.id} service={service} onToggle={() => updateStore((current) => ({ ...current, services: current.services.map((item) => item.id === service.id ? { ...item, active: !item.active } : item) }))}/>)}</div></>}
    {view === "staff" && <><SectionHeading eyebrow="A thoughtful team" title="Staff" body="Meet the people who make each ALBA ritual feel personal."/><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{store.staff.map((member) => <article key={member.id} className="border border-border bg-background p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-secondary font-display text-xl text-forest">{member.name.split(" ").map((part) => part[0]).join("")}</span><div><p className="text-sm font-medium">{member.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{member.role}</p></div></div><div className="mt-5 flex justify-between border-t border-border pt-4 text-xs"><span>{member.specialty}</span><span className="flex items-center gap-1"><Star className="size-3 fill-champagne text-champagne"/>{member.rating}</span></div><p className="mt-3 text-[10px] text-muted-foreground">{store.appointments.filter((item) => item.therapist === member.name).length} appointments in this demo</p></article>)}</div></>}
    {view === "customers" && <><SectionHeading eyebrow="The people behind each visit" title="Guests" body="A look at your guest community, built from demo appointments."/><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search guests" className="mt-6 rounded-none sm:max-w-72"/><div className="mt-5 grid gap-2">{Array.from(new Map(store.appointments.map((item) => [item.email, item])).values()).filter((item) => `${item.customer} ${item.phone} ${item.email}`.toLowerCase().includes(search.toLowerCase())).map((customer) => <div key={customer.email} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border border-border bg-background p-4 sm:grid-cols-[1fr_1.2fr_1fr_auto]"><div className="min-w-0"><p className="truncate text-xs font-medium">{customer.customer}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{customer.phone}</p></div><p className="hidden truncate text-xs text-muted-foreground sm:block">{customer.email}</p><p className="hidden text-xs text-muted-foreground sm:block">{store.appointments.filter((item) => item.email === customer.email).length} visits</p><span className="text-[10px] text-forest">{customer.status}</span></div>)}</div></>}
    {view === "invoices" && <><SectionHeading eyebrow="Every visit, thoughtfully recorded" title="Invoices & payments" body="Payment status and invoice-ready booking records."/><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Revenue", formatRupees(revenue)], ["Paid", store.appointments.filter((item) => item.payment === "Paid").length], ["Pending", store.appointments.filter((item) => item.payment === "Pending").length], ["Partial", store.appointments.filter((item) => item.payment === "Partial").length]].map(([label, value]) => <div key={label} className="border border-border bg-background p-4"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-2 font-display text-2xl">{value}</p></div>)}</div><div className="mt-5 border border-border bg-background"><AppointmentList rows={store.appointments} onStatus={changeStatus} invoice/></div></>}
    {view === "offers" && <><SectionHeading eyebrow="A welcome from ALBA" title="Offers & promotions" body="Your active guest offers, ready to share."/><div className="mt-6 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{store.offers.map((offer) => <article key={offer.id} className="bg-background p-6"><span className="alba-eyebrow">{offer.active ? "Active offer" : "Paused"}</span><h3 className="mt-4 font-display text-3xl">{offer.name}</h3><p className="mt-2 text-2xl text-forest">{offer.discount}</p><p className="mt-2 text-xs text-muted-foreground">Code · {offer.code}</p><Button variant="outline" className="mt-5 rounded-none" onClick={() => updateStore((current) => ({ ...current, offers: current.offers.map((item) => item.id === offer.id ? { ...item, active: !item.active } : item) }))}>{offer.active ? "PAUSE OFFER" : "ACTIVATE OFFER"}</Button></article>)}</div></>}
    {view === "reviews" && <><SectionHeading eyebrow="Guest feedback" title="Reviews" body="Featured guest notes appear on the public ALBA site."/><div className="mt-6 grid gap-3">{store.reviews.map((review) => <article key={review.id} className="grid gap-4 border border-border bg-background p-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div><div className="flex items-center gap-1"><span className="text-xs font-medium">{review.customer}</span>{Array.from({ length: review.rating }, (_, i) => <Star key={i} className="size-3 fill-champagne text-champagne"/>)}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">“{review.quote}”</p><p className="mt-2 text-[10px] text-muted-foreground">{review.service}</p></div><Button variant={review.featured ? "default" : "outline"} className="rounded-none" onClick={() => updateStore((current) => ({ ...current, reviews: current.reviews.map((item) => item.id === review.id ? { ...item, featured: !item.featured } : item) }))}>{review.featured ? "FEATURED · REMOVE" : "FEATURE ON SITE"}</Button></article>)}</div></>}
    {view === "reports" && <><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><SectionHeading eyebrow="A clearer picture" title="Reports" body="Guest visits and revenue at a glance."/><div className="flex gap-2"><select aria-label="Report date range" value={period} onChange={(event) => setPeriod(event.target.value)} className="border border-border bg-background px-3 text-xs">{["Today", "This week", "This month", "Last month", "Custom"].map((item) => <option key={item}>{item}</option>)}</select><Button onClick={exportCsv} variant="outline" className="rounded-none"><Download/> EXPORT CSV</Button></div></div><div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="border border-border bg-background p-5"><p className="text-sm font-medium">Bookings · {period}</p><MiniChart appointments={store.appointments}/><div className="mt-4 flex justify-between text-[10px] text-muted-foreground"><span>7 days ago</span><span>Today</span></div></div><div className="border border-border bg-background p-5"><p className="text-sm font-medium">Revenue by treatment</p><div className="mt-5 grid gap-4">{store.services.slice(0, 5).map((service) => { const count = store.appointments.filter((item) => item.serviceId === service.id && item.payment === "Paid").length; const percent = Math.max(9, Math.round(count / Math.max(1, store.appointments.length) * 100)); return <div key={service.id}><div className="flex justify-between gap-3 text-xs"><span className="truncate">{service.name}</span><span>{formatRupees(count * service.price)}</span></div><div className="mt-2 h-1.5 bg-secondary"><div className="h-full bg-forest" style={{ width: `${percent}%` }}/></div></div>; })}</div></div></div></>}
    {view === "settings" && <><SectionHeading eyebrow="A calm, considered experience" title="Settings" body="Manage your demo preferences and reset the studio to its starting state."/><div className="mt-7 grid gap-5 lg:grid-cols-2"><div className="border border-border bg-background p-6"><p className="font-display text-3xl">Studio details</p><div className="mt-5 grid gap-4">{[["Business name", "ALBA WELLNESS"], ["Location", "Ahmedabad, Gujarat, India"], ["Opening hours", "Every day · 10:00 AM–8:00 PM"], ["Currency", "INR · Prices include applicable tax"]].map(([label, value]) => <div key={label} className="grid gap-2"><Label>{label}</Label><Input defaultValue={value} className={fieldClass}/></div>)}</div><Button variant="outline" className="mt-5 rounded-none" onClick={() => toast.success("Studio preferences saved.")}>SAVE PREFERENCES</Button></div><div className="border border-border bg-background p-6"><p className="font-display text-3xl">Demo data</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Restore the original appointments, guests, treatments, offers, reviews and profile details for another walkthrough.</p><p className="mt-4 text-xs text-muted-foreground">Changes are saved in this browser only.</p><Button variant="outline" className="mt-6 rounded-none" onClick={resetDemo}>RESET DEMO DATA</Button></div></div></>}
    </div></main></div></div>;
}

function AppointmentList({ rows, onStatus, invoice = false }: { rows: AlbaAppointment[]; onStatus: (id: string, status: AlbaAppointment["status"]) => void; invoice?: boolean }) {
  const { store, updateStore } = useAlbaDemo();
  return <div className="divide-y divide-border">{rows.map((item) => <article key={item.id} className="grid gap-3 p-4 sm:grid-cols-[minmax(0,1.15fr)_minmax(0,1fr)_auto] sm:items-center sm:px-5"><div className="min-w-0"><p className="truncate text-xs font-medium">{item.customer} <span className="font-normal text-muted-foreground">· {item.reference}</span></p><p className="mt-1 truncate text-[10px] text-muted-foreground">{getService(store, item.serviceId).name} · {prettyDate(item.date)} · {item.time}</p></div><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-[10px] text-muted-foreground"><span>{item.therapist}</span><span>{formatRupees(item.amount)}</span><span className={item.status === "Confirmed" ? "text-forest" : ""}>{item.status}</span><span>{item.payment}</span></div><div className="flex flex-wrap gap-2">{invoice ? <><Button size="sm" variant="outline" onClick={() => toast.success(`Invoice ${item.reference} prepared.`)}><FileText/> INVOICE</Button>{item.payment !== "Paid" && <Button size="sm" variant="outline" onClick={() => { updateStore((current) => ({ ...current, appointments: current.appointments.map((appointment) => appointment.id === item.id ? { ...appointment, payment: "Paid" } : appointment) })); toast.success("Payment marked paid."); }}>MARK PAID</Button>}</> : item.status === "Confirmed" || item.status === "Pending" ? <><Button size="sm" variant="outline" onClick={() => onStatus(item.id, "Completed")}>COMPLETE</Button><Button size="sm" variant="outline" onClick={() => onStatus(item.id, "Cancelled")}>CANCEL</Button></> : <Button size="sm" variant="outline" onClick={() => onStatus(item.id, "Confirmed")}>REOPEN</Button>}</div></article>)}</div>;
}

function ServiceAdminCard({ service, onToggle }: { service: AlbaService; onToggle: () => void }) { return <article className="overflow-hidden border border-border bg-background"><img src={albaImages[service.image as keyof typeof albaImages] ?? albaImages.treatment} width={1200} height={1008} alt="" className="aspect-[16/8] w-full object-cover"/><div className="p-4"><div className="flex justify-between gap-3"><div><p className="text-[10px] text-muted-foreground">{service.category} · {service.duration} min</p><h3 className="mt-1 font-display text-2xl">{service.name}</h3></div><span className="text-sm">{formatRupees(service.price)}</span></div><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className={`text-[10px] ${service.active ? "text-forest" : "text-muted-foreground"}`}>{service.active ? "Available to book" : "Hidden from guests"}</span><Button size="sm" variant="outline" onClick={onToggle}>{service.active ? "DISABLE" : "ENABLE"}</Button></div></div></article>; }

function MiniChart({ appointments }: { appointments: AlbaAppointment[] }) { const counts = Array.from({ length: 7 }, (_, day) => appointments.filter((item) => item.date === localDate(day)).length); const max = Math.max(1, ...counts); return <div className="mt-6 flex h-36 items-end gap-2 border-b border-border">{counts.map((count, i) => <div key={i} className="flex flex-1 flex-col items-center justify-end gap-2"><span className="text-[9px] text-muted-foreground">{count}</span><div className="w-full max-w-10 bg-forest/75" style={{ height: `${Math.max(9, count / max * 95)}%` }}/></div>)}</div>; }
function popularService(appointments: AlbaAppointment[], services: AlbaService[]) { const counts = services.map((service) => [service.name, appointments.filter((item) => item.serviceId === service.id).length] as const).sort((a, b) => b[1] - a[1]); return counts[0]?.[0] ?? "Signature Head Spa"; }